# Generated by Django 2.2.4 on 2019-09-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('numeroSeguroSocial', models.IntegerField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(blank=True, max_length=30, null=True)),
                ('labor', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('correoElectronico', models.EmailField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('codigoPostal', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='programasCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaCapacitacion', models.TextField(blank=True, max_length=50, null=True)),
                ('descripcionCapacitacion', models.TextField(blank=True, max_length=100, null=True)),
                ('tipoCapacitacion', models.TextField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCapacitacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.empleados')),
                ('programas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.programasCapacitacion')),
            ],
        ),
    ]
