# Generated by Django 2.2.4 on 2019-10-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, choices=[('Unidad de Producción', 'Unidad de Producción'), ('', 'Fases'), ('Unidad de Empaque', 'Unidad de Empaque')], default='', max_length=20, null=True)),
                ('puesto', models.CharField(blank=True, choices=[('', 'Áreas y Puestos'), ('1.- Unidad de Empaque', (('Recepción de Frutas', 'Recepción de Frutas'), ('Desflore', 'Desflore'), ('Lavador de Fomi', 'Lavador de Fomi'), ('Armador de Carga', 'Armador de Carga'), ('Evaluador de Fruta', 'Evaluador de Fruta'), ('Clasificación', 'Clasificación'), ('Selección', 'Selección'), ('Selladoras', 'Selladoras'), ('Pasador de Frutas', 'Pasador de Frutas'), ('Empacador', 'Empacador'), ('Repesado de Cajas Empacadas.', 'Repesado de Cajas Empacadas.'), ('Desmane', 'Desmane'), ('Estibador', 'Estibador'), ('Pegador de Carton', 'Pegador de Carton'), ('Preparación de Mezcla PosCosecha', 'Preparación de Mezcla PosCosecha'), ('Limpieza', 'Limpieza'), ('Dedo Suelto', 'Dedo Suelto'), ('Bodega de Cartón', 'Bodega de Cartón'), ('Evaluador de Cajas', 'Evaluador de Cajas'), ('Jefe de Empaque', 'Jefe de Empaque'))), ('2.- Unidad Producción', (('Deshije', 'Deshije'), ('Aplicadores de Herbicidas', 'Aplicadores de Herbicidas'), ('Desflore Manual', 'Desflore Manual'), ('Cajeteo', 'Cajeteo'), ('Saneo', 'Saneo'), ('Paleo', 'Paleo'), ('Fertilización', 'Fertilización'), ('Riego y Bombeo', 'Riego y Bombeo'), ('Chapeo de Rondas', 'Chapeo de Rondas'), ('Picador de Matas', 'Picador de Matas'), ('Desvio de Hijos y Rearme', 'Desvio de Hijos y Rearme'), ('Técnico de Producción', 'Técnico de Producción'), ('Jefe de Área', 'Jefe de Área'), ('Cosecha', 'Cosecha'), ('Embolse y Amarre.', 'Embolse y Amarre.'), ('Fitosanitarios', 'Fitosanitarios'), ('Seguridad', 'Seguridad'), ('Responsable de Bodegas y Almacén', 'Responsable de Bodegas y Almacén'), ('Taller y Mantenimiento.', 'Taller y Mantenimiento')))], default='', max_length=20, null=True)),
                ('actividad', models.CharField(blank=True, max_length=500, null=True)),
                ('tiposRiesgo', models.CharField(blank=True, choices=[('Físico', 'Físico'), ('Quimico', 'Quimico'), ('Físico y Quimico', 'Físico y Quimico'), ('', 'Tipos de riesgo')], default='', max_length=20, null=True)),
                ('regionAnatomica', models.CharField(blank=True, max_length=200, null=True)),
                ('eppUtilizar', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='planAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirigido', models.CharField(blank=True, max_length=300, null=True)),
                ('concepto', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='programasCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaCapacitacion', models.TextField(blank=True, max_length=50, null=True)),
                ('descripcionCapacitacion', models.TextField(blank=True, max_length=100, null=True)),
                ('tipoCapacitacion', models.TextField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('numeroSeguroSocial', models.IntegerField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidad', models.CharField(choices=[('', 'Nacionaidad'), ('Mexicana', 'Mexicana'), ('Extranjero', 'Extranjero')], default='', max_length=20)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('correoElectronico', models.EmailField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('codigoPostal', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.areas')),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCapacitacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaCapacitacion', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('capacitacionTeminada', models.BooleanField(default=True, verbose_name='Capacitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.empleados')),
                ('programas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.programasCapacitacion')),
            ],
        ),
    ]
