# Generated by Django 2.2.6 on 2019-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='fase',
            field=models.CharField(blank=True, choices=[('', 'Fases'), ('Unidad de Producción', 'Unidad de Producción'), ('Unidad de Empaque', 'Unidad de Empaque')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='tiposRiesgo',
            field=models.CharField(blank=True, choices=[('Físico y Quimico', 'Físico y Quimico'), ('Físico', 'Físico'), ('', 'Tipos de riesgo'), ('Quimico', 'Quimico')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nacionalidad',
            field=models.CharField(choices=[('Extranjero', 'Extranjero'), ('Mexicana', 'Mexicana'), ('', 'Nacionaidad')], default='', max_length=20),
        ),
    ]
