# Generated by Django 2.2.4 on 2019-08-26 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='planCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaCapacitacion', models.TextField(blank=True, max_length=50, null=True)),
                ('descripcionCapacitacion', models.TextField(blank=True, max_length=100, null=True)),
                ('fechaCapacitacion', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.empleados')),
            ],
        ),
    ]
