# Generated by Django 2.2.4 on 2019-09-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programascapacitacion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
