# Generated by Django 2.2.4 on 2019-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plananual',
            name='concepto',
        ),
        migrations.AddField(
            model_name='plananual',
            name='contenido',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plananual',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plananual',
            name='dirigidoaquien',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plananual',
            name='duracion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plananual',
            name='objetivoG',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plananual',
            name='objetivoe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plananual',
            name='tecnicas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plananual',
            name='tema',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='fase',
            field=models.CharField(blank=True, choices=[('', 'Fases'), ('Unidad de Producción', 'Unidad de Producción'), ('Unidad de Empaque', 'Unidad de Empaque')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='tiposRiesgo',
            field=models.CharField(blank=True, choices=[('', 'Tipos de riesgo'), ('Físico', 'Físico'), ('Físico y Quimico', 'Físico y Quimico'), ('Quimico', 'Quimico')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plananual',
            name='dirigido',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
