# Generated by Django 2.2.4 on 2019-08-26 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0002_plancapacitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='planSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaPlanSalud', models.TextField(blank=True, max_length=100, null=True)),
                ('descripcionTemaSalud', models.TextField(blank=True, max_length=100, null=True)),
                ('fechaPlanSalud', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='planMantenimieto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaPlanMantenimiento', models.TextField(blank=True, max_length=100, null=True)),
                ('descripcionMantenimiento', models.TextField(blank=True, max_length=100, null=True)),
                ('fechaMantenimiento', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.empleados')),
            ],
        ),
    ]
