# Generated by Django 2.2.4 on 2019-10-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0002_auto_20191008_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='plananual',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='tiposRiesgo',
            field=models.CharField(blank=True, choices=[('Quimico', 'Quimico'), ('Físico y Quimico', 'Físico y Quimico'), ('Físico', 'Físico'), ('', 'Tipos de riesgo')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nacionalidad',
            field=models.CharField(choices=[('Mexicana', 'Mexicana'), ('Extranjero', 'Extranjero'), ('', 'Nacionaidad')], default='', max_length=20),
        ),
    ]
