# Generated by Django 2.2.4 on 2019-08-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0003_planmantenimieto_plansalud'),
    ]

    operations = [
        migrations.CreateModel(
            name='capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCapacitacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='progrmasCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaCapacitacion', models.TextField(blank=True, max_length=50, null=True)),
                ('descripcionCapacitacion', models.TextField(blank=True, max_length=100, null=True)),
                ('tipoCapacitacion', models.TextField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='planmantenimieto',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='plansalud',
            name='empleado',
        ),
        migrations.DeleteModel(
            name='planCapacitacion',
        ),
        migrations.DeleteModel(
            name='planMantenimieto',
        ),
        migrations.DeleteModel(
            name='planSalud',
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='programas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surBananas.progrmasCapacitacion'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='programas',
            field=models.ManyToManyField(through='surBananas.capacitacion', to='surBananas.progrmasCapacitacion'),
        ),
    ]
