# Generated by Django 2.2 on 2020-03-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0003_auto_20191023_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='fase',
        ),
        migrations.AddField(
            model_name='empleados',
            name='fase',
            field=models.CharField(blank=True, choices=[('Nutricion', 'Nutricion'), ('Area 2', 'Area 2'), ('Unidad de Producción', 'Unidad de Producción'), ('Area 4', 'Area 4'), ('Unidad de Empaque', 'Unidad de Empaque'), ('Area 5', 'Area 5'), ('Sigatoka', 'Sigatoka'), ('Area 1', 'Area 1'), ('Seguridad', 'Seguridad'), ('Area 3', 'Area 3'), ('Riego', 'Riego'), ('Otros', 'Otros'), ('', 'Areas'), ('Moko', 'Moko')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='fechaEliminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='motivoEliminacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='tiposRiesgo',
            field=models.CharField(blank=True, choices=[('', 'Tipos de riesgo'), ('Físico y Quimico', 'Físico y Quimico'), ('Quimico', 'Quimico'), ('Físico', 'Físico')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellidoMaterno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellidoPaterno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='celular',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='codigoEmpleado',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='codigoPostal',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='correoElectronico',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombres',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='numeroSeguroSocial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='status',
            field=models.BooleanField(default=True, verbose_name='¡Dar de baja!'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='incidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalfaltas', models.IntegerField(blank=True, null=True)),
                ('codigoEmpleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surBananas.empleados')),
            ],
        ),
    ]
