# Generated by Django 2.2.4 on 2019-08-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0004_auto_20190826_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='domicilio',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='empleados',
            name='codigoPostal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
