# Generated by Django 2.2.4 on 2019-08-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0005_auto_20190827_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='colonia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
