# Generated by Django 2.2.4 on 2019-09-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0006_empleados_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
