# Generated by Django 2.2.4 on 2019-09-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0007_auto_20190903_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='apelidoMaterno',
            new_name='apellidoMaterno',
        ),
        migrations.RenameField(
            model_name='empleados',
            old_name='apelidoPaterno',
            new_name='apellidoPaterno',
        ),
    ]
