# Generated by Django 2.2.4 on 2019-09-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0008_auto_20190903_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
