# Generated by Django 2.2.4 on 2019-09-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0009_auto_20190904_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
