# Generated by Django 2.2.4 on 2019-09-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surBananas', '0014_auto_20190906_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
